Dojo/Dojo/Models/ViewModels/dojoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dojo.Models.ViewModels
{
    public class DojoViewModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name ="Nombre")]
        public string Nombre { get; set; }
        [Required]
        [StringLength(500)]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    }
}

Dojo/Dojo/Controllers/DojoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dojo.Models;
using Dojo.Models.ViewModels;

namespace Dojo.Controllers
{
    public class DojoController : Controller
    {
        // GET: Dojo
        public ActionResult Dojos()
        {
            List<ListdojoViewModel> listDojo;
            using(DBDojoEntities db = new DBDojoEntities())
            {
                listDojo = (from d in db.Dojo_Tbl
                            select new ListdojoViewModel
                            {
                                Id = d.Id,
                                Nombre = d.Nombre,
                                Descripcion = d.Descripcion
                            }).ToList();
            }
            return View(listDojo);
        }

        public ActionResult NuevoDojo()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult NuevoDojo(DojoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBDojoEntities db = new DBDojoEntities())
                    {
                        var dojoTabla = new Dojo_Tbl();
                        dojoTabla.Nombre = model.Nombre;
                        dojoTabla.Descripcion = model.Descripcion;

                        db.Dojo_Tbl.Add(dojoTabla);
                        db.SaveChanges();
                    }

                    return Redirect("Dojos/");
                }

                return View(model);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        public ActionResult EditarDojo(int Id)
        {
            DojoViewModel model = new DojoViewModel();
            using(DBDojoEntities bd = new DBDojoEntities())
            {
                var oDojo = bd.Dojo_Tbl.Find(Id);
                model.Nombre = oDojo.Nombre;
                model.Descripcion = oDojo.Descripcion;
                model.Id = oDojo.Id;
            }
            
            return View(model);
        }


        [HttpPost]
        public ActionResult EditarDojo(DojoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBDojoEntities db = new DBDojoEntities())
                    {
                        var dojoTabla = db.Dojo_Tbl.Find(model.Id);
                        dojoTabla.Nombre = model.Nombre;
                        dojoTabla.Descripcion = model.Descripcion;
                        dojoTabla.Id = model.Id;

                        db.Entry(dojoTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("~/Dojo/Dojos");
                }

                return View(model);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        public ActionResult EliminarDojo(int Id)
        {
            using (DBDojoEntities bd = new DBDojoEntities())
            {
                var oDojo = bd.Dojo_Tbl.Find(Id);
                bd.Dojo_Tbl.Remove(oDojo);
                bd.SaveChanges();
                
            }

            return Redirect("~/Dojo/Dojos");
        }
    }
}

Dojo/Dojo/Views/Dojo/Dojos.cshtml
@model List<Dojo.Models.ViewModels.ListdojoViewModel>
@{
    ViewBag.Title = "Dojos";
}

<br />
<br />
<div class="row">
    <div class="col-md-12">

        <h2>@ViewBag.Title</h2>
        <div class="row" style="text-align:right;padding:5px">
            <a href="~/Dojo/NuevoDojo" class="btn btn-primary">Crear Dojo</a>
        </div>
        <table class="table">
            <tr>
                <th> </th>
                <th>#</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th> </th>
                <th> </th>
            </tr>
            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        <a class="btn btn-primary" href="~/Reto/Retos/@item.Id">Ver Dojo</a>

                    </td>
                    <td> @item.Id </td>
                    <td> @item.Nombre </td>
                    <td> @item.Descripcion </td>
                    <td>
                        <a class="btn btn-default" href="~/Dojo/EditarDojo/@item.Id">Editar</a>

                    </td>
                    <td>
                        <a class="btn btn-danger" href="~/Dojo/EliminarDojo/@item.Id">Eliminar</a>
                    </td>
                </tr>

            }

        </table>
        
    </div>
</div>

Dojo/Dojo/Views/Dojo/EditarDojo.cshtml
@model Dojo.Models.ViewModels.DojoViewModel
@{
    ViewBag.Title = "Editar Dojo";
}

<br />
<br />
<br />

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("EditarDojo", "Dojo", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.Id)
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })

            </div>

            <div>
                @Html.LabelFor(d => d.Descripcion)
                @Html.TextBoxFor(d => d.Descripcion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
            </div>


            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>

}

Dojo/Dojo/Views/Dojo/NuevoDojo.cshtml
@model Dojo.Models.ViewModels.DojoViewModel
@{
    ViewBag.Title = "Crear Dojo";
}

<br />
<br />

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("NuevoDojo", "Dojo", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">

            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })

            </div>

            <div>
                @Html.LabelFor(d => d.Descripcion)
                @Html.TextBoxFor(d => d.Descripcion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
            </div>


            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>

}