Dojo/Dojo/Models/ViewModels/RetoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dojo.Models.ViewModels
{
    public class RetoViewModel
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "#Dojo")]
        public int Id_Dojo { get; set; }
        [Required]
        [StringLength(500)]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha apertura")]
        public DateTime Fecha_Apertura { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha cierre")]
        public DateTime Fecha_Cierre { get; set; }
        [Required]
        [Display(Name = "Valoración del reto")]
        public int? Valoracion_Reto { get; set; }
    }
}

Dojo/Dojo/Controllers/RetoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dojo.Models;
using Dojo.Models.ViewModels;

namespace Dojo.Controllers
{
    public class RetoController : Controller
    {
        // GET: Reto

        
        public ActionResult Retos(int Id)
        {
            List<ListretosViewModel> listReto;
            
            using (DBDojoEntities db = new DBDojoEntities())
            {
                listReto = (from d in db.Reto_Tbl
                            where d.Id_Dojo == Id
                            select new ListretosViewModel
                            {
                                Id = d.Id,
                                Id_Dojo = d.Id_Dojo,
                                Descripcion = d.Descripcion,
                                Fecha_Apertura = d.Fecha_Apertura,
                                Fecha_Cierre = d.Fecha_Cierre,
                                Valoracion_Reto = d.Valoracion_Reto
                                
                            }).ToList();
            }
            return View(listReto);
        }


        public ActionResult MiembrosReto(int Id /*,int id_dojo*/)
        {
            List<ListMiembroViewModel> listMiembros;

            using (DBDojoEntities db = new DBDojoEntities())
            {
                listMiembros = (from d in db.Miembros_Tbl
                            where d.Id_Reto == Id //&& d.Id_Dojo==id_dojo
                            select new ListMiembroViewModel
                            {
                                Id = d.Id,
                                Id_Dojo = d.Id_Dojo,
                                Nombre = d.Nombre,
                                E_mail = d.E_mail,
                                Id_Reto = d.Id_Reto,
                                Puntuacion_Reto = d.Puntuacion_Reto

                            }).ToList();
            }
            return View(listMiembros);
        }

        public ActionResult NuevoReto()
        {
            return View();
        }


        [HttpPost]
        public ActionResult NuevoReto(RetoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBDojoEntities db = new DBDojoEntities())
                    {
                        var RetoTabla = new Reto_Tbl();
                        RetoTabla.Id_Dojo = model.Id_Dojo;
                        RetoTabla.Descripcion = model.Descripcion;
                        RetoTabla.Fecha_Apertura = model.Fecha_Apertura;
                        RetoTabla.Fecha_Cierre = model.Fecha_Cierre;
                        RetoTabla.Valoracion_Reto = model.Valoracion_Reto;

                        db.Reto_Tbl.Add(RetoTabla);
                        db.SaveChanges();
                    }

                    var ruta = "/Reto/Retos/" + model.Id_Dojo;

                    return Redirect(ruta);
                }

                return View(model);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }


        public ActionResult EditarReto(int Id)
        {
            RetoViewModel model = new RetoViewModel();
            using (DBDojoEntities bd = new DBDojoEntities())
            {
                var oReto = bd.Reto_Tbl.Find(Id);
                model.Id_Dojo = oReto.Id_Dojo;
                model.Descripcion = oReto.Descripcion;
                model.Fecha_Apertura = oReto.Fecha_Apertura;
                model.Fecha_Cierre = oReto.Fecha_Cierre;
                model.Valoracion_Reto = oReto.Valoracion_Reto;
                model.Id = oReto.Id;
            }
            return View(model);
        }


        [HttpPost]
        public ActionResult EditarReto(RetoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBDojoEntities db = new DBDojoEntities())
                    {
                        var retoTabla = db.Reto_Tbl.Find(model.Id);
                        retoTabla.Id_Dojo = model.Id_Dojo;
                        retoTabla.Descripcion = model.Descripcion;
                        retoTabla.Fecha_Apertura = model.Fecha_Apertura;
                        retoTabla.Fecha_Cierre = model.Fecha_Cierre;
                        retoTabla.Valoracion_Reto = model.Valoracion_Reto;
                        retoTabla.Id = model.Id;

                        db.Entry(retoTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    var ruta = "~/Reto/Retos/" + model.Id_Dojo;
                    return Redirect(ruta);
                }

                return View(model);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        public ActionResult EliminarReto(int Id)
        {
            string ruta = null;
            using (DBDojoEntities bd = new DBDojoEntities())
            {
                var oReto = bd.Reto_Tbl.Find(Id);
                bd.Reto_Tbl.Remove(oReto);
                bd.SaveChanges();
                ruta = "~/Reto/Retos/" + oReto.Id_Dojo;
            }

            return Redirect(ruta);
        }
    }
}

Dojo/Dojo/Views/Reto/EditarReto.cshtml
@model Dojo.Models.ViewModels.RetoViewModel
@{
    ViewBag.Title = "Editar Reto";
}

<br />
<br />
<br />

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("EditarReto", "Reto", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.Id)
            <div>
                @Html.LabelFor(d => d.Id_Dojo)
                @Html.TextBoxFor(d => d.Id_Dojo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Id_Dojo, null, new { @class = "red" })

            </div>

            <div>
                @Html.LabelFor(d => d.Descripcion)
                @Html.TextBoxFor(d => d.Descripcion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.Valoracion_Reto)
                @Html.TextBoxFor(d => d.Valoracion_Reto, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Valoracion_Reto, null, new { @class = "red" })
            </div>

            <br />
            <div>
                @Html.LabelFor(d => d.Fecha_Apertura)<br />
                @Html.EditorFor(d => d.Fecha_Apertura, null, new { @class = "red" })
            </div>
            <br />
            <div>
                @Html.LabelFor(d => d.Fecha_Cierre)<br />
                @Html.EditorFor(d => d.Fecha_Cierre, null, new { @class = "red" })
            </div>

            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>

}

Dojo/Dojo/Views/Reto/MiembrosReto.cshtml
@model List<Dojo.Models.ViewModels.ListMiembroViewModel>
@{
    ViewBag.Title = "Miembros Reto";
}

<br />
<br />

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th># Dojo</th>
                <th>Nombre</th>
                <th>E-mail</th>
                <th>Reto</th>
                <th>Puntuación en el reto</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td> @item.Id </td>
                    <td>@item.Id_Dojo</td>
                    <td> @item.Nombre </td>
                    <td> @item.E_mail </td>
                    <td>@item.Id_Reto</td>
                    <td>@item.Puntuacion_Reto</td>
                </tr>
            }
        </table>
    </div>
</div>

Dojo/Dojo/Views/Reto/NuevoReto.cshtml
@model Dojo.Models.ViewModels.RetoViewModel
@{
    ViewBag.Title = "Crear reto ";
}



@using (Html.BeginForm("NuevoReto", "Reto", FormMethod.Post))
{
    <div class="row">
        
        <div class="col-md-12">
            <h2>@ViewBag.Title</h2>
            <div>
                @Html.LabelFor(d => d.Id_Dojo)
                @Html.TextBoxFor(d => d.Id_Dojo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Id_Dojo, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.Descripcion)
                @Html.TextBoxFor(d => d.Descripcion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Descripcion, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.Valoracion_Reto)
                @Html.TextBoxFor(d => d.Valoracion_Reto, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Valoracion_Reto, null, new { @class = "red" })
            </div>
            <br />
            <div>
                @Html.LabelFor(d => d.Fecha_Apertura)<br />
                @Html.EditorFor(d => d.Fecha_Apertura, null, new { @class = "red" })
            </div>
            <br />
            <div>
                @Html.LabelFor(d => d.Fecha_Cierre)<br />
                @Html.EditorFor(d => d.Fecha_Cierre, null, new { @class = "red" })
            </div>

            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>

}

Dojo/Dojo/Views/Reto/Retos.cshtml
@model List<Dojo.Models.ViewModels.ListretosViewModel>
@{
    ViewBag.Title = "Retos";
}

<br />
<br />
<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-md-12">
        <div class="row" style="text-align:right;padding:5px">
            <a href="~/Reto/NuevoReto" class="btn btn-primary">Crear Reto</a>
        </div>
        <table class="table">
            <tr>
                <th> </th>
                <th>#</th>
                <th>Dojo</th>
                <th>Fecha Apertura</th>
                <th>Fecha Cierre</th>
                <th>Valoración Reto</th>
                <th>Descripción Reto</th>
                <th> </th>
                <th> </th>
                <th> </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        <a href="~/Reto/MiembrosReto/@item.Id" class="btn btn-primary">Ver miembros</a>
                    </td>
                    <td> @item.Id </td>
                    <td> @item.Id_Dojo </td>
                    <td> @item.Fecha_Apertura</td>
                    <td> @item.Fecha_Cierre </td>
                    <td> @item.Valoracion_Reto </td>
                    <td> @item.Descripcion </td>
                    <td>
                        <a class="btn btn-default" href="~/Reto/EditarReto/@item.Id">Editar</a>

                    </td>
                    <td>
                        <a class="btn btn-danger" href="~/Reto/EliminarReto/@item.Id">Eliminar</a>
                    </td>
                    
                </tr>
            }
        </table>
        
    </div>
</div>