Dojo/Dojo/Models/ViewModels/MiembroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dojo.Models.ViewModels
{
    public class MiembroViewModel
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "#Dojo*")]
        public int Id_Dojo { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Nombre*")]
        public string Nombre { get; set; }
        [Required]
        [StringLength(50)]
        [EmailAddress]
        [Display(Name = "E-mail*")]
        public string E_mail { get; set; }
        [Display(Name = "Reto")]
        public int? Id_Reto { get; set; }
        [Display(Name = "Puntuación en el reto")]
        public int? Puntuacion_Reto { get; set; }
    }
}

Dojo/Dojo/Controllers/MiembroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dojo.Models;
using Dojo.Models.ViewModels;

namespace Dojo.Controllers
{
    public class MiembroController : Controller
    {
        // GET: Miembro
        public ActionResult Miembros()
        {
            List<ListMiembroViewModel> listMiembros;
            using (DBDojoEntities db = new DBDojoEntities())
            {
                listMiembros = (from d in db.Miembros_Tbl
                            select new ListMiembroViewModel
                            {
                                Id = d.Id,
                                Id_Dojo = d.Id_Dojo,
                                Nombre = d.Nombre,
                                E_mail = d.E_mail,
                                Id_Reto = d.Id_Reto,
                                Puntuacion_Reto = d.Puntuacion_Reto
                            }).ToList();
            }
            return View(listMiembros);
        }

        public ActionResult AñadirReto()
        {
            List<ListretosViewModel> listRetos;
            using (DBDojoEntities db = new DBDojoEntities())
            {
                listRetos = (from d in db.Reto_Tbl
                             //where d.Id_Dojo == id_dojo
                                select new ListretosViewModel
                                {
                                    Id = d.Id,
                                    Id_Dojo = d.Id_Dojo,
                                    Descripcion = d.Descripcion,
                                    Fecha_Apertura = d.Fecha_Apertura,
                                    Fecha_Cierre = d.Fecha_Cierre,
                                    Valoracion_Reto = d.Valoracion_Reto
                                }).ToList();
            }
            return View(listRetos);
        }

        public ActionResult NuevoMiembro()
        {
            return View();
        }


        [HttpPost]
        public ActionResult NuevoMiembro(MiembroViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBDojoEntities db = new DBDojoEntities())
                    {
                        var miembroTabla = new Miembros_Tbl();
                        miembroTabla.Id_Dojo = model.Id_Dojo;
                        miembroTabla.Nombre = model.Nombre;
                        miembroTabla.E_mail = model.E_mail;
                        miembroTabla.Id_Reto = model.Id_Reto;
                        miembroTabla.Puntuacion_Reto = model.Puntuacion_Reto;
                        
                        db.Miembros_Tbl.Add(miembroTabla);
                        db.SaveChanges();
                    }

                    return Redirect("Miembros/");
                }

                return View(model);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        public ActionResult EditarMiembro(int Id)
        {
            MiembroViewModel model = new MiembroViewModel();
            using (DBDojoEntities bd = new DBDojoEntities())
            {
                var oMiembro = bd.Miembros_Tbl.Find(Id);
                model.Id_Dojo = oMiembro.Id_Dojo;
                model.Nombre = oMiembro.Nombre;
                model.E_mail = oMiembro.E_mail;
                model.Id_Reto = oMiembro.Id_Reto;
                model.Puntuacion_Reto = oMiembro.Puntuacion_Reto;
                model.Id = oMiembro.Id;
            }
            return View(model);
        }

        public ActionResult EditarMiembro(int Id, int id_dojo)
        {
            MiembroViewModel model = new MiembroViewModel();
            using (DBDojoEntities bd = new DBDojoEntities())
            {
                var oMiembro = bd.Miembros_Tbl.Find(Id);
                model.Id_Dojo = oMiembro.Id_Dojo;
                model.Nombre = oMiembro.Nombre;
                model.E_mail = oMiembro.E_mail;
                model.Id_Reto = id_dojo;
                model.Puntuacion_Reto = oMiembro.Puntuacion_Reto;
                model.Id = oMiembro.Id;
            }
            return View(model);
        }



        [HttpPost]
        public ActionResult EditarMiembro(MiembroViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBDojoEntities db = new DBDojoEntities())
                    {
                        var miembroTabla = db.Miembros_Tbl.Find(model.Id);
                        miembroTabla.Id_Dojo = model.Id_Dojo;
                        miembroTabla.Nombre = model.Nombre;
                        miembroTabla.E_mail = model.E_mail;
                        miembroTabla.Id_Reto = model.Id_Reto;
                        miembroTabla.Puntuacion_Reto = model.Puntuacion_Reto;
                        miembroTabla.Id = model.Id;

                        db.Entry(miembroTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    var ruta = "~/Miembro/Miembros/" + model.Id_Dojo;
                    return Redirect(ruta);
                }

                return View(model);
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        public ActionResult EliminarMiembro(int Id)
        {
            string ruta = null;
            using (DBDojoEntities bd = new DBDojoEntities())
            {
                var oMiembro = bd.Miembros_Tbl.Find(Id);
                bd.Miembros_Tbl.Remove(oMiembro);
                bd.SaveChanges();
                ruta = "~/Miembro/Miembros/";
            }

            return Redirect(ruta);
        }
    }
}

Dojo/Dojo/Views/Miembro/AñadirReto.cshtml
@model List<Dojo.Models.ViewModels.ListretosViewModel>
@{
    ViewBag.Title = "Añadir Reto";
}

<br />
<br />
<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Dojo</th>
                <th>Fecha Apertura</th>
                <th>Fecha Cierre</th>
                <th>Valoración Reto</th>
                <th>Descripción Reto</th>
                <th> </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td> @item.Id </td>
                    <td> @item.Id_Dojo </td>
                    <td> @item.Fecha_Apertura</td>
                    <td> @item.Fecha_Cierre </td>
                    <td> @item.Valoracion_Reto </td>
                    <td> @item.Descripcion </td>
                    <td>
                        <div style="text-align:right;">
                            <input value="Unirse" class="btn btn-primary" type="submit" />
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

Dojo/Dojo/Views/Miembro/EditarMiembro.cshtml
@model Dojo.Models.ViewModels.MiembroViewModel
@{
    ViewBag.Title = "Editar Miembro";
}

<br />
<br />
<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("EditarMiembro", "Miembro", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.Id)
            <div>
                @Html.LabelFor(d => d.Id_Dojo)
                @Html.TextBoxFor(d => d.Id_Dojo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Id_Dojo, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.E_mail)
                @Html.TextBoxFor(d => d.E_mail, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.E_mail, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Id_Reto)
                @Html.TextBoxFor(d => d.Id_Reto, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Id_Reto, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Puntuacion_Reto)
                @Html.TextBoxFor(d => d.Puntuacion_Reto, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Puntuacion_Reto, null, new { @class = "red" })
            </div>
            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}

Dojo/Dojo/Views/Miembro/Miembros.cshtml
@model List<Dojo.Models.ViewModels.ListMiembroViewModel>
@{
    ViewBag.Title = "Miembros";
}

<br />
<br />

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">
        <div class="row" style="text-align:right;padding:5px">
            <a href="~/Miembro/NuevoMiembro" class="btn btn-primary">Añadir Miembro</a>
        </div>
        <table class="table">
            <tr>
                <th></th>
                <th>#</th>
                <th># Dojo</th>
                <th>Nombre</th>
                <th>E-mail</th>
                <th>Reto</th>
                <th>Puntuación en el reto</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a href="~/Miembro/AñadirReto/@item.Id_Dojo" class="btn btn-primary">Añadir reto</a>
                    </td>
                    <td> @item.Id </td>
                    <td>@item.Id_Dojo</td>
                    <td> @item.Nombre </td>
                    <td> @item.E_mail </td>
                    <td>@item.Id_Reto</td>
                    <td>@item.Puntuacion_Reto</td>
                    <td>
                        <a class="btn btn-default" href="~/Miembro/EditarMiembro/@item.Id">Editar</a>

                    </td>
                    <td>
                        <a class="btn btn-danger" href="~/Miembro/EliminarMiembro/@item.Id">Eliminar</a>
                    </td>
                </tr>

            }
        </table>
    </div>
</div>

Dojo/Dojo/Views/Miembro/NuevoMiembro.cshtml
@model Dojo.Models.ViewModels.MiembroViewModel
@{
    ViewBag.Title = "Nuevo Miembro";
}

<br />
<br />

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("NuevoMiembro", "Miembro", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <h5>Los datos con (*) son requeridos.</h5>
            <div>
                @Html.LabelFor(d => d.Id_Dojo)
                @Html.TextBoxFor(d => d.Id_Dojo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Id_Dojo, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.E_mail)
                @Html.TextBoxFor(d => d.E_mail, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.E_mail, null, new { @class = "red" })
            </div>
            
            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>
}